<?php

return array (
  'EmptyWebsiteURL' => 'Không để trống URL site',
  'EmptyWebsiteName' => 'Chưa có tên website',
  'config_global' => 'Cấu hình chung',
  'config_site' => 'Cấu hình site',
  'Config' => 'Cấu hình',
  'ConfigModule' => 'Cấu hình module',
  'ConfigDisplay' => 'Cấu hình hiển thị',
  'MapDriver' => 'Kiểu bản đồ',
  'SignUpAPI' => 'Đăng ký API',
  'SiteLatitude' => 'Vĩ độ',
  'SiteLongitude' => 'Kinh độ',
  'SiteClosureMode' => 'Chế độ đóng cửa site',
  'CloseSite0' => 'Site hoạt động bình thường',
  'CloseSite1' => 'Đóng cửa site chỉ có Quản trị tối cao truy cập',
  'CloseSite2' => 'Đóng cửa site Người điều hành chung truy cập',
  'CloseSite3' => 'Đóng cửa site Tất cả admin truy cập',
  'EnableLangURL' => 'Kích hoạt tính năng ngôn ngữ trên url',
  'DisableLangURL' => 'Tắt ngôn ngữ trên url',
  'AdminPrefix' => 'Tiền tố trang quản trị',
  'Follow' => 'Theo dõi',
  'Update' => 'Cập nhật',
  'CurrentVersion' => 'Phiên bản hiện tại',
);
