<?php

return array (
  'Language' => 'Ngôn ngữ',
  'ListLanguage' => 'Quản lý ngôn ngữ',
  'TranslateLang' => 'Dịch thuật',
  'AddLang' => 'Thêm ngôn ngữ',
  'SelectLang' => 'Lựa chọn ngôn ngữ',
  'LangDefault' => 'Mặc định',
  'LangActive' => 'Kích hoạt',
  'LangName' => 'Tên hiển thị',
  'LangCode' => 'Mã ngôn ngữ',
  'LangFlag' => 'Cờ',
  'NoteSelectFlag' => 'Chọn cờ cho ngôn ngữ',
  'ImportLanguage' => 'Tải lên ngôn ngữ',
  'ViewFileLang' => 'Đọc file ngôn ngữ',
  'SuccessDelLang' => 'Xoá ngôn ngữ thành công',
  'ErrorDelLang' => 'Xoá ngôn ngữ không thành công. Vui lòng kiểm tra lại.',
  'SuccessSetDefault' => 'Đặt ngôn ngữ mặc định thành công',
  'ErrorSetDefault' => 'Đặt ngôn ngữ mặc định không thành công. Vui lòng kiểm tra lại.',
  'SuccessChangeWeight' => 'Thay đổi vị trí thành công',
  'ErrorChangeWeight' => 'Thay đổi vị trí không thành công',
  'ErrorAlreadyExistLang' => 'Ngôn ngữ [:name] đã tồn tại',
  'AddKeyLang' => 'Thêm từ mới',
  'ImportSampleTranslation' => 'Nhập bản dịch mẫu',
  'SuccessImportTranslation' => 'Nhập bản dịch mẫu thành công',
  'ErrorExportLanguage' => 'Lỗi không xuất được file ngôn ngữ',
  'SuccessExportLanguage' => 'Xuất file ngôn ngữ thành công',
  'ErrorNoteFindLang' => 'Ngôn ngữ này chưa có file ngôn ngữ',
  'SuccessNoteFindLang' => 'Tồn tại các file ngôn ngữ tương ứng',
  'ChooseLanguage' => 'Chọn ngôn ngữ',
);
