<?php

return array (
  'mainModule' => 'Quản lý Modules',
  'AddModule' => 'Thêm Module',
  'UpModFile' => 'Tải lên Module',
  'DelMod' => 'Xoá Module',
  'EditMod' => 'Thay đổi thông tin Module',
  'ActiveMod' => 'Kích hoạt Modules',
  'InfoMod' => 'Thông tin Modules',
  'EmptyModule' => 'Không có Module nào được tìm thấy',
  'SuccessfulDelMod' => 'Xoá Module "<strong>[:module]</strong>" thành công',
  'SuccessUploadMod' => 'Tải lên Module thành công',
  'ErrorUpModEmptyJson' => 'File tải lên không phải là Module',
  'ErrorModuleAlreadyExists' => 'Module này đã tồn tại',
  'ErrorDelModule' => 'Không thể xoá Module "<strong>[:module]</strong>" vì đang được sử dụng trên ngôn ngữ khác',
  'icon' => 'Biểu tượng',
  'LogAddSuccessModule' => '[:name] đã tải lên Module ":title" thành công',
  'LogInstallSuccessModule' => '[:name] đã cài đặt Module ":title" thành công',
  'LogDeleteSuccessModule' => '[:name] đã xoá Module ":title" thành công',
  'LogUninstallSuccessModule' => '[:name] đã gỡ cài đặt Module ":title" thành công',
  'ErrorDelModuleMember' => 'Không thể xoá Module "[Members]" vì sẽ gây lỗi hệ thống',
  'Reinstall' => 'Cài đặt lại',
  'FuncName' => 'Tên chức năng',
  'FunctionNameCustom' => 'Tên chức năng tuỳ chỉnh',
  'SampleModule' => 'Module mẫu',
  'MesSuccessRegisterModule' => 'Đăng ký Module :module thành công',
  'MesSuccessRegisterModFunc' => 'Đăng ký Function :func thành công',
  'MesSuccessRegisterModLang' => 'Đăng ký gói ngôn ngữ Module :module thành công',
  'MesSuccessActiveAssetsModule' => 'Kích hoạt tài nguyên Module :module thành công',
  'MesInstallSuccessModule' => 'Cài đặt Module ":module" thành công',
);
