<?php

return array (
  'Language' => 'Language',
  'ListLanguage' => 'List Language',
  'TranslateLang' => 'Translate',
  'AddLang' => 'Add Lang',
  'SelectLang' => 'Language selection',
  'LangDefault' => 'Default',
  'LangActive' => 'Active',
  'LangName' => 'Display name',
  'LangCode' => 'Language code',
  'LangFlag' => 'Flag',
  'NoteSelectFlag' => 'Select the flag for the language',
  'ImportLanguage' => 'Import Language',
  'ViewFileLang' => 'Read language file',
  'SuccessDelLang' => 'Successful language deletion',
  'ErrorDelLang' => 'Language deletion failed. Please check again.',
  'SuccessSetDefault' => 'Set the default language successfully',
  'ErrorSetDefault' => 'Set the default language to be unsuccessful. Please check again.',
  'SuccessChangeWeight' => 'Successful change of position',
  'ErrorChangeWeight' => 'Position change failed',
  'ErrorAlreadyExistLang' => 'Language [:name] already exists',
  'AddKeyLang' => 'Add key languge',
  'ImportSampleTranslation' => 'Import Sample Translation',
  'SuccessImportTranslation' => 'Success Import Translation',
  'ErrorExportLanguage' => 'Error Export Language',
  'SuccessExportLanguage' => 'Success Export Language',
  'ErrorNoteFindLang' => 'This language does not yet have a language file',
  'SuccessNoteFindLang' => 'Corresponding language files exist',
  'ChooseLanguage' => 'Choose language',
);
