<?php

return array (
  'mainModule' => 'Manager Modules',
  'AddModule' => 'Add Module',
  'UpModFile' => 'Upload Module',
  'DelMod' => 'Delete Module',
  'EditMod' => 'Change Module information',
  'ActiveMod' => 'Active Modules',
  'InfoMod' => 'Info Modules',
  'EmptyModule' => 'No modules were found',
  'SuccessfulDelMod' => 'Deleting Module "<strong>[:module]</strong>" successfully',
  'SuccessUploadMod' => 'Upload Module successfully',
  'ErrorUpModEmptyJson' => 'Upload file is not Module',
  'ErrorModuleAlreadyExists' => 'This module already exists',
  'ErrorDelModule' => 'Cannot remove Module "<strong>[:module]</strong>" because it is being used in another language',
  'icon' => 'Icons',
  'LogAddSuccessModule' => '[:name] upload Module ":title" success',
  'LogInstallSuccessModule' => '[:name] install Module ":title" success',
  'LogDeleteSuccessModule' => '[:name] delete Module ":title" success',
  'LogUninstallSuccessModule' => '[:name] uninstall Module ":title" success',
  'ErrorDelModuleMember' => 'Cannot remove the "[Members]" module because it will cause a system error',
  'Reinstall' => 'Reinstall',
  'FuncName' => 'Function name',
  'FunctionNameCustom' => 'Function name custom',
  'SampleModule' => 'Sample module',
  'MesSuccessRegisterModule' => 'Module registration :module is successful',
  'MesSuccessRegisterModFunc' => 'Function registration :func is successful',
  'MesSuccessRegisterModLang' => 'Register module language pack :module successfully',
  'MesSuccessActiveAssetsModule' => 'Activate the resource Module :module successfully',
  'MesInstallSuccessModule' => 'Install Module ":module" success',
);
